//Create a user
//Extension: REST Client - per testim 
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Erza",
    "email": "egashi@gmail.com",
    "password": "1234567",
    "confPassword": "1234567",
    "role": "admin"
}
